/** Declaration file generated by dts-gen */

export = ncmb;

declare class ncmb {
    constructor(apikey: any, clientkey: any, config: any);

    DataStore(name: any, ...args: any[]): any;

    createSignature(url: any, method: any, query: any, timestamp: any, signatureMethod: any, signatureVersion: any, fqdn: any, apikey: any, clientkey: any, dataResponse: any): any;

    enableResponseValidation(value: any): void;

    get(key: any): any;

    getResponseValidation(): any;

    request(opts: any, callback: any): any;

    requestScript(opts: any, callback: any): any;

    set(key: any, val: any): any;

}

